# Generated by Django 2.2 on 2020-07-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='district',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='division',
            field=models.CharField(choices=[('Barishal ', 'Barishal'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], default='Rajshahi', max_length=20),
        ),
    ]
