# Generated by Django 2.2 on 2020-07-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200722_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='750', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='450', editable=False, null=True),
        ),
    ]
