# Generated by Django 2.2 on 2020-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200728_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
