# Generated by Django 2.2 on 2020-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200802_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='division',
            field=models.CharField(choices=[('Barishal', 'Barishal'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], default='Rajshahi', max_length=20),
        ),
    ]
