name: Testing
on: push

jobs:
  testing:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Run Djnago unit tests
      run: |
        pip3 install -r requirements.txt
        python3 manage.py test
